/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Ticket;
import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.sql.SQLOutput;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import java.util.Scanner;

import static com.fasterxml.jackson.databind.jsonFormatVisitors.JsonValueFormat.UUID;
import static java.util.UUID.randomUUID;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println("there is something wrong");
            return;
        }
        while(option!=7){
            System.out.println("choose option");
            System.out.println("1.Sign Up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book Seat");
            System.out.println("6. Cancel my booking");
            System.out.println("7. Exit the app");
            option = scanner.nextInt();
            switch(option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignup = scanner.next();
                    System.out.println("enter the password too signup");
                    String passwordTosignUp = scanner.next();
//                    User userToSignUp = new User(nameToSignup,passwordTosignUp,
//                            UserServiceUtil.hashPassword(passwordTosignUp),
//                            new ArrayList<>(),UUID,randomUUID().toString());
                    User userToSignUp = new User(
                            nameToSignup,
                            passwordTosignUp,
                            UserServiceUtil.hashPassword(passwordTosignUp),
                            new ArrayList<>(),
                            randomUUID().toString()   // userId
                    );

                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:
                    System.out.println("enter username to login");
                    String nameToLogin = scanner.next();
                    System.out.println("enter the password to login");
                    String passwordToLogin = scanner.next();
//                    User userToLogin = new User(nameToLogin,passwordToLogin,
//                        UserServiceUtil.hashPassword(passwordToLogin),
//                        new ArrayList<>(),UUID,randomUUID().toString());
//                    try{
//                        userBookingService = new UserBookingService(userToLogin);
//                    } catch (IOException e) {
//                        throw new RuntimeException(e);
//                    }

                    User userToLogin = new User(
                            nameToLogin,              // name
                            passwordToLogin,          // password
                            passwordToLogin,          // hashPassword (use actual hash later)
                            new ArrayList<Ticket>(),  // must be Ticket list, not Object
                            "USER-" + nameToLogin     // userId or whatever ID system you use
                    );
                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }


                        break;
                case 3:
                    System.out.println("fetching your Bookings");
                    userBookingService.fetchBookings();
                    break;
                case 4:
                    System.out.println("Type your source Station");
                    String source = scanner.next();
                    System.out.println("Type yoour destination station");
                    String dest = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source,dest);

            }
        }
    }
}
